### ISSUE TITLE
SSL connnection with AWS ELB

### ISSUE THREAD

**Issue by brechmos** [eclipse/paho.mqtt.python#102]
I have an EMQTT daemon running on a couple AWS/EC2s behind a load balancer. I have the ports pointing at the load balancer and can telnet <loadbalancer> 1883 just fine. I created a certificate for the AWS loadbalancer and assigned it to port 8883, which seemed to be fine.

I then tried using the python paho mqtt code (https://pypi.python.org/pypi/paho-mqtt/1.1) to send a message through the load balancer.

I downloaded the certifiate using "aws acm get-certificate --certificate-arn <arn>" and put the CertificateChain section into aws_ca.pem and Certificate into aws_cert.pem.

```
tls = {'ca_certs':"aws_ca.pem", 'certfile': 'aws_cert.pem', 'tls_version': ssl.PROTOCOL_TLSv1, 'ciphers': None}

publish.single(topic="topic_1", payload=json.dumps({'test': 'test'}), qos=2,
hostname="<loadbalancer>", port=8883, keepalive=60, tls=tls)
```

but it fails with ssl errors.

```
ciphers=self._tls_ciphers)
File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
ciphers=ciphers)
File "/usr/lib/python2.7/ssl.py", line 544, in __init__
self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: SSL PEM lib (_ssl.c:2603)
```

I suspect I might have the tls part incorrect and I have to admit the certs / ssl confuses me still.

I would appreciate any ideas on how to make this type of secure connection through the load balancer.

**Comment by PierreF** [comment]
I think your problem is that certfile could not be defined without keyfile. certfile/keyfile is the *client* certificate and its associated key.

In TLS/SSL, your server always have a certificate. This certificate is validated by the client using ca_certs. But you could also have another certificate, a client certificate used by the server to authenticate the client. In this case (and only in this cause) you should provide both certfile and keyfile.

If your client are authenticated using a username/password, you should just remove certfile option and it should work.

**Comment by PierreF** [comment]
Issue seems solved. Feel free to reopen if issue persist.
