### ISSUE TITLE
how to set the topic will be consume only once?

### ISSUE THREAD

**Issue by lioncui** [eclipse/paho.mqtt.python#127]
some web app services, there subscribe the same topic,
when the client publish message, i hope  the topic will be consume only once.
how do it?

**Comment by PierreF** [comment]
Hi,

if i understand correctly, you have two web applications subscribed to the same topic and when a client publish a message you want that this message to be received only by one web application instead of both ?

This is a message queue pattern. And MQTT is a pub-sub protocol, so you can't do this with just MQTT.
Possible solution depending on your requirements include:

* Using different topic per web application
* De-duplicating message on the web application side
* Forwarding all MQTT message to an message queue and have your web applications binding on the message queue.
* Probably other :)

**Comment by lioncui** [comment]
@PierreF Thank you very much.
