### ISSUE TITLE
Best way to handle IPv4

### ISSUE THREAD

**Issue by richmondwatkins** [eclipse/paho.mqtt.python#154]
What is the best way to handle a router that doesn't support IPv6? I recently discovered that I could not get the socket to create a connection on my home router while it was working at my office. I was able to get other mqtt connections to work from a node.js library and the MQTT.fx mac app but never from paho.mqtt.python. After using nettop to monitor my traffic I discovered that paho was trying to force mqtt connections on IPv6 while the others were using IPv4. Then I found out that my ATT router doesn't support IPv6. 

As a temporary solution, I'm resolving the hostname as IPv4 in client.py before trying to create the connection like so: `host = socket.gethostbyname(self._host)`. 

Is there a better way to handle this though? I'd obviously like to leave the source code alone if possible. Any thoughts with this? 

Thanks.

**Comment by PierreF** [comment]
To be sure I correctly understand the issue:

* You are connecting to something like client.connect("home.mydomain.com")
* home.mydomain.com do resolve to an IPv6 (and an IPv4)
* Your current network don't allow IPv4

It that the case, at first I would think there is an issue with your current network. As it let paho.mqtt.python/Python/your system think IPv6 works but it don't.
Usually, on a non-working IPv6 network, since your don't have an IPv6 on your machine connection to IPv6 socket are not tried (or fail very fast).

So if my initial understanding of the issue is correct, could you confirm that you have (or not) an IPv6 associated with your laptop while at your office ?

**Comment by richmondwatkins** [comment]
So to give context, I'm connecting to an AWS iOT endpoint.

I will be at the office tomorrow and can check.

What is weird is that both the MQTT.fx app and AWS iOT node.js SDK both connect as expected. When I use nettop to monitor connections I see that they both try it over IPv4 right away. This SDK is the only one I've seen so far that only tries it over IPv6.

I'm not super well versed in networking so please let me know if I need to clarify any of this more.

**Comment by richmondwatkins** [comment]
Observing the connection with nettop at my office now. It never tries to connect with IPv6. It starts and stays with IPv4.

**Comment by PierreF** [comment]
With MQTT.fx and/or AWS iOT node.js SDK ?

I don't know for them, but paho-mqtt Python will use IPv6 and/or IPv4 depending on what is available. 
Normally it should not try IPv6 if not available or fallback very quickly to IPv4.

What is done (by the Python library) is:
* retrieve address use getaddrinfo: this method should return both IPv6 and IPv4 address
* try each address
** if connection fail try the next one
** if connection success, use that connection

If your network don't have IPv6, creating the socket should fail immediately (your OS will refuse to try connect to this IPv6 because you can't reach this IPv6 address, since your don't have IPv6 network).

Example in my situation:
```
>>> socket.getaddrinfo('www.google.fr', 443, 0, socket.SOCK_STREAM)                  
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('74.125.206.94', 443)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2a00:1450:400c:c04::5e', 443, 0, 0))]
# Note: the IPv4 is the first. Somewhere getaddrinfo know that IPv4 is preferred

# If i try anyway
>>> sock = socket.socket(socket.AF_INET6, socket.SOCK_STREAM, 6)
>>> sock.connect('2a00:1450:400c:c04::5e')
OSError: [Errno 101] Network is unreachable
# Error occur immediately 
```

This happen because the IPv6 2a00:1450:400c:c04::5e could not be reachable from my system which does not have any IPv6:
```
ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::546e:cc0:480d:5651  prefixlen 64  scopeid 0x20<link>   # link IPv6 does not count
```

Under linux you can check the route used to reach an IP with:
```
$ ip route get 2a00:1450:400c:c04::5e
unreachable 2a00:1450:400c:c04::5e [...]
```

If your system think this address is reachable but it's not, there is some issue with your system/network. In this case your should probably try to fix this problem.

If you are using Python 2.7+ or 3.2+ you may try to specify bind_address='0.0.0.0' to connect(). It may work (it seems to work on Linux) but I'm don't know how standard it is and may break on other system.

**Comment by richmondwatkins** [comment]
I gave the MQTT.fx and node.js SDK as examples to show that I am able to connect to the same endpoint on my network using other MQTT libraries and apps.  It may very well be some sort of issue with my network but other libraries and apps are able to connect on it just fine. 

For me the IPv6 immediate failure that you described never happens. It just hangs seemingly forever.

I am using a basic ATT U-Verse modem router combo. I have a neighbor with the exact same setup that I will try with tomorrow. I'll be curios to see if it is just local to me or if it happens for everyone that uses the same kind of router and service provider.

**Comment by richmondwatkins** [comment]
Tested at my neighbors house who is also using ATT as their internet provider and was not able to connect. It hung trying to connect with IPv6 just like it does with mine. MQTT.fx and the node.js library worked just fine.

**Comment by richmondwatkins** [comment]
Looking at the nettop connections on my mac it looks like MQTT.fx and every other mqtt app or sdk I use never tries to connect on IPv6. They all default to IPv4.

**Comment by ralight** [comment]
Would you be able to reproduce the test that @PierreF did? I mean:

    import socket
    socket.getaddrinfo('your endpoint', port, 0, socket.SOCK_STREAM

then report the (anonymised if you wish!) result so we can see what type of addresses get returned?

**Comment by ralight** [comment]
You could also try connecting to test.mosquitto.org - that supports both IPv4 and IPv6 and I've connected to it many times with the Python client from an IPv4 only network.

**Comment by richmondwatkins** [comment]
Here is my setup and output

```
>>> import socket
>>> socket.getaddrinfo('a3pzb0u64rd1gp.iot.us-east-1.amazonaws.com', 8888, 0, socket.SOCK_STREAM)
[(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2406:da00:ff00::36a4:27bd', 8888, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2406:da00:ff00::22c2:50dc', 8888, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2406:da00:ff00::3402:59a', 8888, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2406:da00:ff00::6b15:1e06', 8888, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2406:da00:ff00::3400:770a', 8888, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2406:da00:ff00::3657:ad13', 8888, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('52.0.119.10', 8888)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('54.164.39.189', 8888)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('52.2.5.154', 8888)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('107.21.30.6', 8888)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('34.194.80.220', 8888)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('54.87.173.19', 8888))]
```

**Comment by PierreF** [comment]
I still think this is an system bugs or misconfiguration.
On my systems (Ubuntu, Fedora and Windows 10), IPv4 are always returned before IPv6. Manual page state that application should use order returned by getaddrinfo, so it's logical that Python try IPv6. The fact that other library works may only indicate that they don't follow this recommendation.

A workaround for this systems bugs, you could be to try to force the bind_address when calling connect() to '0.0.0.0' which is invalid for IPv6 (at least on Ubuntu... not sure about the portability of such hack).

If you want to investigate on the root cause, I'm pretty sure it's a network misconfiguration. getaddrinfo should return IPv6 addresses before IPv4 only if they are usable. That means that your system think the given IPv6 address (2406:da00:...) is reachable. This should only be true if your system has an IPv6 with a configured IPv6 gateway... which should NOT occur if your current network does not have IPv6.
Checking which addresses (IPv4 and IPv6) are present on your system and the routing could help you to find the cause.
Maybe your router is mis-configured to provide an IPv6 on your LAN network but don't have internet IPv6 connection ?

**Comment by ralight** [comment]
I got this, which puts the IPv4 addresses first and fails quickly even if I try to connect to an IPv6 address.

```
>>> import socket
>>> socket.getaddrinfo('a3pzb0u64rd1gp.iot.us-east-1.amazonaws.com', 8888, 0, socket.SOCK_STREAM)
[(2, 1, 6, '', ('34.194.80.220', 8888)), (2, 1, 6, '', ('107.21.30.6', 8888)), (2, 1, 6, '', ('54.87.173.19', 8888)), (2, 1, 6, '', ('54.164.39.189', 8888)), (2, 1, 6, '', ('52.2.5.154', 8888)), (2, 1, 6, '', ('52.0.119.10', 8888)), (10, 1, 6, '', ('2406:da00:ff00::3657:ad13', 8888, 0, 0)), (10, 1, 6, '', ('2406:da00:ff00::3402:59a', 8888, 0, 0)), (10, 1, 6, '', ('2406:da00:ff00::3400:770a', 8888, 0, 0)), (10, 1, 6, '', ('2406:da00:ff00::22c2:50dc', 8888, 0, 0)), (10, 1, 6, '', ('2406:da00:ff00::36a4:27bd', 8888, 0, 0)), (10, 1, 6, '', ('2406:da00:ff00::6b15:1e06', 8888, 0, 0))]

```

I agree with @PierreF, it seems like there may be a misconfiguration somewhere. Does your computer have an IPv6 IP address associated with it?

**Comment by richmondwatkins** [comment]
Ok so I had to switch the "Configure IPv6" setting on my mac to "Link-local only".

Then on my raspberry pi (which I was also having the issue on) I had to add the following to `/etc/sysctl.conf`

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
```

To be honest I don't fully understand why all this made a difference and I don't know if changing the pi settings will cause issues down the road. I need to do some reading up on IPv6 and networking in general.

Thanks you both for you help!
