### ISSUE TITLE
Incomplete handling of some socket errors

### ISSUE THREAD

**Issue by jamesmyatt** [eclipse/paho.mqtt.python#188]
There are a couple of places where the error number associated with a `socket.error` is checked against `(errno.EINPROGRESS, errno.EWOULDBLOCK, EAGAIN)` and all other exceptions are re-raised. However, when the error number is in this list, there is no action, which is probably wrong.

For example:

* https://github.com/eclipse/paho.mqtt.python/blob/develop/src/paho/mqtt/client.py#L859
* https://github.com/eclipse/paho.mqtt.python/blob/develop/src/paho/mqtt/client.py#L258

**Comment by PierreF** [comment]
The one in reconnect seems fine for me.
If only means that reconnect in fact didn't reconnected, and self._sock stay None, which only cause later call to loop() to re-try connection.

The one in _socketpair_compat could be problematic. I agree that if such error occur, I think later code will fail (probably hang). That being said, I not sure those error could occur since it's using localhost, which should not fail.

**Comment by engineeringentropy** [comment]
Looks like this is still an issue in 1.4.0:
ERROR:__main__:Unknown exception while waiting for conclusion of application: local variable 'sock' referenced before assignment
Traceback (most recent call last):
  File "databaser.py", line 81, in <module>
    databaser = MqttDatabaser(caFile=args.ca, keyFile=args.key, certFile=args.cert, queue=dataQueue)
  File "/mnt/c/Users/.../mqtt/databasermqtt.py", line 53, in __init__
    mqtt.connect("XXXX", 8883, 10)
  File "/mnt/c/Users/..../venv/lib/python3.6/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/mnt/c/Users/..../venv/lib/python3.6/site-packages/paho/mqtt/client.py", line 974, in reconnect
    sock,
UnboundLocalError: local variable 'sock' referenced before assignment.

The above was obtained by dropping a VPN connection before running the application. 
sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0)) throws EAGAIN, which then falls through to 
sock = self._ssl_context.wrap_socket(
                    sock,
a few lines later.

I'm not sure what the correct behaviour should be.

**Comment by engineeringentropy** [comment]
For anyone else getting this error with certificates where the server either disappears or isn't found:
The exception handler at client.py:963 can be changed to reraise the socket.error (remove the if-clause), and then let the background loop catch the error and run with it.

**Comment by MattBrittan** [comment]
Support for `socket.error` was [dropped in 2021](https://github.com/eclipse/paho.mqtt.python/commit/4910b785a49b989e150eb11e87f7ca5aad38992a) so I'm going to close this issue. It's likely that there are other related issues with exception handling (and a few open issues) but I don't think this specific issue is still of relevance. 

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
