### ISSUE TITLE
disconnect() and messages with qos > 0

### ISSUE THREAD

**Issue by FabianInostroza** [eclipse/paho.mqtt.python#196]
What happens/should happen to messages with qos > 0 that haven't been delivered by the client if I call disconnect?

**Comment by PierreF** [comment]
Hi,

If what you want to achieve is something like:
```
def on_connect(client, userdata, flags, rc):
    if rc == 0:
        client.publish(..., qos=0)
        client.publish(..., qos=0)
        client.disconnect()
```

then this should works. Obviously, since it's QoS == 0, a network error may cause the message to be lost, but if network is flawless, messages will be delivered.

What code do is to queue message (QoS == 0 and disconnect message) in the same output buffer which is a FIFO. So if you publish message before calling disconnect, the QoS==0 message will be published before sending the disconnect. In addition loop_forever (or loop_start) will not exit before the output buffer is empty (or any error, like a network error, occur).

But be careful, if you try to publish QoS == 0 message *before* the connection is established, the message is dropped. You must not call publish with qos=0 before the connection. That's why in my example code I've done the publish in the on_connect callback.

Finally if all you want is just connect, send few messages and disconnect, look at [publish helper](https://github.com/eclipse/paho.mqtt.python#id2), which basically do what I suggest.

Hope it answer your question. If not feel free to reopen.

**Comment by FabianInostroza** [comment]
Thanks, you answered the case when QoS = 0 and I suppose that what you said is also valid for QoS > 0.

What I'm trying to do is to save some energy, I have a device with a 3G modem.
I tried increasing the keepalive interval and just leaving pppd disable the internet connection after some time without activity but this resulted in big delay in the data transmission because the connection with the broker was not marked invalid promptly after a new publish (and pppd session).
I wanted to try a new approach, close the connection with the broker when I know that I will not publish messages for while but I also worried about messages being lost.
I'm using the client with the loop_start() call and QoS = 1.

**Comment by PierreF** [comment]
QoS > 0 are sightly different, because they may not be sent immediately, because they respect max_inflight message count.
Because of this they may be queued in a different queue, and then the disconnect could be sent before the QoS > 0 message queue is purged.

The best solution I see is to count the number of message submitted (just before calling publish()) and and number of message published (using callback on_publish). When the two number match, is mean all submitted message are published and then you can disconnect.

**Comment by FabianInostroza** [comment]
Thanks, do you think there is it necessary to use a lock on the counter?
Why not implement a method on the client that returns the number of pending messages?, the client should already know this

**Comment by PierreF** [comment]
It depends where each access to the counter are done. I think you will only have 3 access:
* Read the counter (most likely for logging or checking if the value is 0)
* Increasing the counter (before call to publish)
* Decreasing the counter (in on_publish callback)

The Paho library is mono-threaded. Therefor all processing (including call to user callback) are done in the same thread. If all your access are done in callback, no longer is required.
If only read of the counter is done outside the callback, you may be okay without lock (it means that when you read a value, it may already have changed).

But if you increase the counter outside the callback, the lock should be mandatory.

If you are unsure, use a lock, the cost is rather small (230 ns on my laptop, Python 3.5)

**Comment by FabianInostroza** [comment]
So in my case it's mandatory to use a lock, because there is no callback function for when a message is being queued by a call to publish().

I encountered some problems while implementing this logic. Calling disconnect() terminates the thread used by the library (the documentation doesn't say it), so after calling reconnect() or connect_async() nothing happens. 
To be able to reconnect it was necessary to call disconnect() followed by loop_stop() (to set self._thread to None) and to reconnect, a call to reconnect() or connect_async() and then loop_start() was necessary.

After a closer look at the library code I think that keeping track of the published messages (with QoS > 0) is not necessary.

Many thanks.
