### ISSUE TITLE
Support for Ubuntu 14.04 users cut off

### ISSUE THREAD

**Issue by NickWaterton** [eclipse/paho.mqtt.python#204]
The recent breaking change to not support versions of python lower than 2.7.9 has left all Ubuntu 14.04 users in the cold.

We are at python 2.7.6, and trying to upgrade would break all our dependencies. I have to stay with V1.2.3 in order to continue to use this library.

I am using TLS V1.1, and I understand that python 2.7.9 is required for TLS V1.2, but I don't understand why V1.3 is not backward compatible with the thousands of Ubuntu 14.04 users out there.

I should be able to use TLS 1.1, but now I can't. Backwards compatibility with existing users should be a priority.

**Comment by PierreF** [comment]
Hi,

support for new features like SNI or more powerful SSL context changed the code that handle TLS setup. New code rely on SSL context. Supporting both old and new method create a more complicated code and make it harder to maintain.

That's why we dropped support for older Python version.

That being said, Ubuntu 14.04 user has the option to go with Python 3.4 which is supported. If your application can't yet run on Python 3, backports.ssl package may be a solution.

**Comment by NickWaterton** [comment]
So you believe that instead of a "harder to maintain" source code library, everyone else should simply:

- Change their operating system
- Change their programming language
- Rewrite their whole program to accommodate your changes.

Whereas I think that you should maintain backwards compatibility.

**Comment by ralight** [comment]
Hi Nick,

You can still get the previous version. To install that specific version with pip, do:

    pip install paho-mqtt==1.2.3

**Comment by swails** [comment]
@NickWaterton - There are many things you can do to use the `paho-mqtt` library on Ubuntu 14.04:

1. As @ralight suggested, use `pip install paho-mqtt==1.2.3` to get a version compatible with your system-level Python
1. Use `virtualenv` to install a Python 2.7.9+
1. Install Python 3.4 using `apt-get` (as suggested by @PierreF)
1. Install the latest version of Python 2.7 from a commercially-backed distribution like miniconda (this is very easy)

There are more than enough (very easy) workarounds that do not require you to change your OS. 
 I also suggest reading [this post](http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html) by a core Python developer that works for Red Hat that makes a strong case for not going out of your way to support older versions of Python.  The basic gist of it is that developers that donate their time should not feel obligated to divert effort to provide gratis support for legacy platforms.  The more appropriate place to take this complaint is to Ubuntu and make the case that it is worth their resources to devote a developer to the paho project to maintain compatibility with their 14.04 LTS release.

**Comment by NickWaterton** [comment]
Or you could remain backwards compatible.

I understand all the workarounds to the problem you have caused. That doesn't help the users of my programs out there, who are contacting me, saying that there is a problem with my program - which traces back to the breaking changes you have introduced.

Imagine if every library developer out there took the same attitude and the chaos that would ensue. If you make major breaking changes (not in beta state, but after many years or deployment), most developers release a major version upgrade (ie V1,x to 2.x).

I donate my time providing useful programs also, but this "legacy platforms should upgrade" attitude (where "legacy" means a year or two old - and Ubuntu 14.04 is two years old) means a lot of work for us library users out there, if you don't handle your release versioning well.

I now have to go back to my users (of my free program) and try to explain this mess, and the "very easy" workarounds. As this is an IoT interface, many of them are new to the field, and don't understand what is "very easy" for us to figure out.

Just wanted you to be aware of the fallout from this decision, and it isn't going well out there. Just in case you thought no-one noticed. We did. And we are not happy.

**Comment by swails** [comment]
Here are more options:

1. Bundle paho-mqtt 1.2.3 in your package distribution and remove it from the set of requirements for your package.  Better yet, put it in a new namespace (e.g., `contrib`) and make the 2 or 3 changes to import statements to support that placement.  I've done this in my own projects before.
1. Submit a PR to this project to restore Python 2.7.6 compatibility (without eliminating features that people have contributed), then add an appropriate entry in the Travis build matrix to test this platform. [This is precisely what I did when I had a vested interest in preserving backwards compatibility in the face of a breaking change last year](https://github.com/eclipse/paho.mqtt.python/pull/54)
1. Chime in [when the discussion about dropping support for old versions of Python is going on](https://github.com/eclipse/paho.mqtt.python/issues/115) -- that issue was open for 7 months and was opened 9 months before 1.3.0 was released.
1. Specify in your package that paho-mqtt 1.2.3 is required -- I'm certain there's a way to do this in a way that will make `pip` install the appropriate paho version.

> Or you could remain backwards compatible.

paho *is* backwards compatible.  Backwards compatibility means API compatibility with older versions of that package -- *not* that the base runtime requirements never change.

> Imagine if every library developer out there took the same attitude

Not hard to imagine -- most do.  Examples: numpy and friends, pip, coverage, [django](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django), ... the list goes on.

> If you make major breaking changes (not in beta state, but after many years or deployment), most developers release a major version upgrade (ie V1,x to 2.x).

This *is* planned.  Many projects change base Python requirements without breaking backwards compatibility in the API and release as minor version changes.  Look at django 1.8 to 1.9 (support for Python 3.2 and 3.3 are dropped), and that's a large, prominent project with a wide user base.  I'm pretty sure numpy did the same kind of thing somewhere in the 1.X line.

> Ubuntu 14.04 is two years old

More than 3 years old.

I've found the process of contributing here open, respectful, and transparent (I'm in no way affiliated with Eclipse or Paho -- I'm a user of the library that has contributed some back).  As someone that maintains projects for free as well, I believe your frustrations and accusations are misplaced.  You can't expect every upstream project developers to embrace the same priorities you do and saddle themselves with extra (boring and irritating) work in their free time to cater to users that never provide input in the public forums of the projects.  If you want your priorities to become paho's priorities, be a proactive contributor.

Barring that, the onus is on you to insulate yourself from any upstream changes that may break your code that is forced to conform to a stricter set of runtime requirements than those upstream projects have committed to.  That's precisely why the `package==<version>` capability is supported in the pip requirements file.

**Comment by Nzbuu** [comment]
As the others have said, your version of Python is fully supported by paho v1.2.3. If you want to use TLS in a more recent version of paho, then you need to use a more recent version of Python.

I would ask Ubuntu why they won't add a newer and more secure version of Python 2.7 to the 14.04 LTS package index. Python v2.6.9 was actually released a month _before_ the first release of Ubuntu 14.04, and there have been a further 5 Ubuntu 14.04 releases since then. There are very good reasons (mainly security) why the core Python development team broke existing conventions to backport the ssl library updates to Python 2.7. See https://www.python.org/dev/peps/pep-0466/.

As the person that implemented the updates that require the new ssl library, I can tell you that it was going to be a **major** headache to maintain support for Python 2.7.8 and earlier while allowing users the required access to the newer, more featured and more secure ssl library, which is why there was a discussion on this first. Furthermore, the number of edge-cases that would have been created would have been a serious security risk.

In the end, I echo what @swails has said; I too am not affiliated with Eclipse or Paho, but I have found my contributions, including these SSL updates, to be gratefully and constructively received. If this is so important to you, then I have no doubt that if you raise a pull request that restores support for SSL in earlier versions of Python without compromising the security and functionality for newer versions, then it will be equally constructively received.

However, if instead you attempt to badger a group of volunteers to change a decision that means much more work for them and has already been agreed multilaterally when your use case is already supported by a previous release, then you're likely to get a short answer.

**Comment by ralight** [comment]
Nick, I'm sure we all feel your frustration. If I'd have been more involved I might have pushed towards a 2.x release, but I've made a conscious decision to let the active people get on with it.

I hope you've got some constructive feedback on how you might work with this.

**Comment by NickWaterton** [comment]
I understand that no-one like criticism of their "baby", and I do contribute to other projects (I just can't contribute to everything...).

I'll note the incompatibility for my code. It's not really a big deal, I'm just passing on a word of caution.

My point is if you supply a library (even if it's free), then you have customers. It should be a red flag if your latest release makes work for these customers (as, if they have to do some work, they may decide to do something entirely different instead). This is how you start to lose an otherwise loyal installed base. Without the installed base, and the customers, you have a dead project.

So don't look at this as a rant against your no doubt excellent work on the latest paho-mqtt python version, but more of a warning of the potential consequences of this kind of incremental release (which I'm saying is not really an incremental release).

**Comment by Nzbuu** [comment]
Here's the view of a CPython core developer: https://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by jbwdevries** [comment]
Consider supporting https://pypi.org/project/backports.ssl , it should be only a matter of changing the ssl import when ssl.SSLContext is not available

**Comment by CarlFK** [comment]
14.04 is EOL (kinda): 
Ubuntu 14.04.6 LTS | Trusty Tahr | Changes | March 7, 2019 | April 2019 | April 2022
https://wiki.ubuntu.com/Releases

I propose closing this.   it's obviously a wont-fix which I'm ok with.

it sounds like there may have been (still is?) a packaging bug and/or maybe version number could be better so that packagers take care so  "normal system updates" don't install a new version that isn't compatible.

**Comment by ralight** [comment]
As Carl suggests, this is now no longer worth keeping open. Ubuntu 14.04 is only supported for security updates through paid commercial offerings, and Python 2 reached end of life over 18 months ago (support for Python 2 remains untouched in the Paho code).
