### ISSUE TITLE
mqtt Connection timed out

### ISSUE THREAD

**Issue by daxiabiluo** [eclipse/paho.mqtt.python#217]
Traceback (most recent call last):
  File "/opt/mqtttext.py", line 161, in <module>
    mqttc.run()
  File "/opt/mqtttext.py", line 76, in run
    self.connect(dedata['MQTT']["IP"], dedata['MQTT']["PORT"], 60)
  File "/python-arm/lib/python2.7/site-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/python-arm/lib/python2.7/site-packages/paho/mqtt/client.py", line 887, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/python-arm/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 110] Connection timed out

Sometimes the above error occurs when the program is started, but sometimes it works normally.What's the problem with this?
This seems to be the first time MQTT connection failed. I use loop_start (). Can I try to reconnect after the first time?

**Comment by PierreF** [comment]
Calling connect() will open the TCP connection. And if the TCP connection fail you get an exception allowing you to known that configuration may be wrong (user entered a bad address and/or port ?)

In your case, if you want to retry the connection, the most straightforward method is to use connect_async() instead of connect() and let loop_start() do the (re)connection. loop_start() will catch such exception and retry to (re)connect later.

**Comment by daxiabiluo** [comment]
Thanks to answer, can be solved by this method

**Comment by hsnhrn** [comment]
Hi Pierre,

I am having the same problem for a publisher. Can you please help me in this too? thanks
