### ISSUE TITLE
Memory only gets released on disconnect

### ISSUE THREAD

**Issue by eifinger** [eclipse/paho.mqtt.python#225]
I observed that the memory usage of my application increases with each call to "client.publish()" and never goes down again. The only way to release the memory is to call "client.disconnect()".

The behavior I would expect is that memory usage goes up and down as messages get removed from the pending/inflight queue. It seems the messages are still referenced somewhere.

I am running a script to test the performance of the IBM IoT Platform and am using their [sdk](https://github.com/ibm-watson-iot/iot-python) which uses this lib.
I set up a connection and publish messages with different QoS, different payload and each different amount of times published.
I closed down on the client.publish method by commenting out the line which calls it in the ibm lib which resulted in no change to the memory usage during the runtime of the program.

Can someone explain to me this behavior or if any of my assumptions are false?

EDIT: The code I'm using can be found here: https://github.com/eifinger/paho-memory-check/blob/master/paho-memory-check.py (Beware I am not a Python programmer ;-))

**Comment by PierreF** [comment]
Your code may have an issue that will cause huge memory consumption: you don't wait for messages to be published before continuing. (I said may, because I looked quickly to ibmiotf).

When you print "Finished sending messages", I think that actually you only queued message to be sent. Therefor you give 1 seconds for all queued message to be sent before getting memory usage. With 100.000 messages it's unlikely that all messages are sent.

For your test to be more accurate, you will need to be sure all messages are sent and acknowledged by the MQTT server.
On the paho library that would means make sure that on_publish callback is called for each message that you publish (at least that the count match).
With the IBM sdk, it may be by looking at "messages" counter. This counter seem incremented each time on_publish is called ([link](https://github.com/ibm-watson-iot/iot-python/blob/master/src/ibmiotf/__init__.py#L185)).

**Comment by eifinger** [comment]
Hi Pierre, thank you!
This was exactly what was causing the memory consumption, I implemented a check of the messages counter before going on.
Thanks again!
