### ISSUE TITLE
stuck at call to message_callback_add

### ISSUE THREAD

**Issue by alborzs** [eclipse/paho.mqtt.python#233]
Run the below code and you will see that it gets stuck at message_callback_add.

```
import sys
import os
import time
import logging

from time import sleep

import paho.mqtt.client as mqtt

mqtt_server_ip      = "10.42.0.1"
mqtt_server_port    = 1884

subscriptions_qos =[("doorStatus/status", 0),
                    ("doorStatus/eol",0)]

def callback_door_status(client, userdata, message):
    logging.debug("Received %s", message.payload)

def on_log(client, userdata, level, buf):
    logging.debug("%s", buf)

def on_connect(client, userdata, flags, rc):
    logging.info("Successfully connected to MQTT with result code %s", str(rc))
    print("before message_callback_add 1")
    client.message_callback_add("doorStatus", callback_door_status)
    print("after message_callback_add")

    (result, _) = client.subscribe(subscriptions_qos)
    if (result == mqtt.MQTT_ERR_SUCCESS):
        logging.info("Successfully subscribed to MQTT topics with result code %s", str(result))

def on_message(client, userdata, msg):
    logging.debug("Received: Topic: %s Body: %s", msg.topic, msg.payload)

def main():
    logger = logging.getLogger('root')
    logging.basicConfig(format='[%(asctime)s %(levelname)s: %(funcName)20s] %(message)s', level=logging.DEBUG)

    client = mqtt.Client("master")
    client.on_log = on_log
    client.on_connect = on_connect
    client.on_message = on_message
    client.connect(mqtt_server_ip, mqtt_server_port, 60)

    client.loop_forever()

if __name__ == '__main__':
    main()
```

This is the output from the code:
```
[2017-09-20 07:06:40,562 DEBUG:               on_log] Received CONNACK (0, 0)
[2017-09-20 07:06:40,562 INFO:           on_connect] Successfully connected to MQTT with result code 0
before message_callback_add 1
```
As you can see from the output, the connection to the broker is established successfully, but right after the first call to message_callback_add the code gets stuck and nothing else happens. At this point the only thing I can do is to kill the process. I have no idea why the code is getting stuck, I have also looked at the documentation and still couldn't find anything.

**Comment by PierreF** [comment]
Hi,
the message_callback_add does not subscribe by itself. It only register a callback that is called if a received message match the associated topic.
Therefor the message_callback_add does not need to be called on each connect, and it's probably easier to call it once for all during client initialization (e.g. at the same time you setup the on_connect and on_message callback).
This will solve your issue.

That being said, there is a bug / undocumented issue in that message_callback_add (or updating/defining any callback) could not be done within a callback. Currently doing so will hang forever due to a deadlock, the code try to acquire the same lock twice.

**Comment by MattBrittan** [comment]
Closing as it looks like an answer was provided.
