### ISSUE TITLE
Some clients keep reconnecting

### ISSUE THREAD

**Issue by knmr** [eclipse/paho.mqtt.python#245]
Im hosting an MQTT Broker in Microsoft Azure for a while. We are getting more and more clients. Recently some clients got stuck in a connection loop (while they were running fine before). After restarting them they run fine for a little and then go back to looping. Restarting the server does not change anything here. That's why I'm assuming it has something to do with the client. Another point worth noting is that the server reports the following events for the loop clients:

> client connected
closing client, reason: new connection request
closed
setting keepalive timeout
client connected

I added a piece of source and a wireshark capture of the reconnect issue.

`try:
	mqttc.connect(mqtt_url, 80, 60)
except:
	print("connect exception")

if __name__ == '__main__':
	_thread.start_new_thread(do_some_work, ())
	mqttc.loop_forever()`

![reconnect_flow](https://user-images.githubusercontent.com/8867038/32434173-9961f86e-c2dd-11e7-99f1-16927a846e7f.png)

**Comment by PierreF** [comment]
I'm not sure to understand what you means by reconnection loop.
Your wireshark capture seems to show ONE client reconnection. It this reconnection (with this delay of 90 seconds between connection/disconnect) happen in loop ?

Your wireshark capture & timing make me think to a keepalive issue. Since your client get disconnected after 90 seconds, which match a 60 seconds keepalive (usual default;  and MQTT protocol say that broker must disconnect client if it don't receive a packet within one and a half times the Keep Alive time period).

Your logs make me wonder if two clients are not using the same clientid ("closing client, reason: new connection request").

Could you give more information about your setup: version of paho, broker used (mosquitto ?) and the keepalive value. Also are you fixing the clientid ? If yes, could you confirm not using the same clientid twice, as this will disconnect the other connection using the same clientid.

**Comment by knmr** [comment]
I can give you that information, but we found the root of the issue. We had a memory leak on our client-side. That's why the connection attempt got cut off and retried the connection. We fixed the leak and added nightly reboot. Looping hasn't happened since.

We used random clientids prior to this issue. It's one of the reasons why we switched to fixed, We had problems identifying the clients.

Sorry for not updating this issue. It completely slipped my mind.
