### ISSUE TITLE
Broken pipe with new asyncio support

### ISSUE THREAD

**Issue by dragomirecky** [eclipse/paho.mqtt.python#260]
Hi,
I am having problem with the latest (develop) version. I think there is an issue with the new support for external event loops added in #235. It works fine for some time, but then it starts raising „broken pipe“ at [this line](https://github.com/eclipse/paho.mqtt.python/blob/0b2b479f74e222c13d05bf9e6171545a1923cb4a/src/paho/mqtt/client.py#L2453).

I think it's because the socket pair `_sockpairW` and `_sockpairR` is being fed periodically at that line, but with external loop, `_sockpairR` is never being read from. After some time, this fills up buffer of the socket pair and starts throwing the exception.  

My current workaround is simple – I just extended [misc_loop](https://github.com/eclipse/paho.mqtt.python/blob/0b2b479f74e222c13d05bf9e6171545a1923cb4a/examples/loop_asyncio.py#L50) with periodic read from `_sockpairR`.  This seems to work.

What do you think is the right approach to fix this issue?

**Comment by vadmium** [comment]
I believe I ran into the same root cause, although the exceptions I saw were all TimeoutError. Here is an excerpt of the backtrace, on Linux using Python 3.6 and Paho v1.2:

```python traceback
  File "usr/lib/python3.6/site-packages/paho/mqtt/client.py", line 980, in publish
  File "usr/lib/python3.6/site-packages/paho/mqtt/client.py", line 2022, in _send_publish
  File "usr/lib/python3.6/site-packages/paho/mqtt/client.py", line 2218, in _packet_queue
TimeoutError: [Errno 110] Connection timed out
```

Our application has its own selector loop, which calls _loop_read_, __write_ and __misc_. The plain _loop_ method is not called, so __sockpairR_ is never read.

So far in my attempt to reproduce the problem, I have seen __sockpairR_'s receive buffer, and then __sockpairW_'s send buffer, fill up with one byte per _publish_ call, which I can monitor with the _netstat_ command. After the send buffer is full, the _send_ call raises EAGAIN, which the Paho library catches and ignores. My theory is that eventually the socket pair's TCP connection will time out, and _send_ will return ETIMEDOUT, which Python will raise as an exception.

I suppose my workaround will be similar to Dragomirecký's: periodically read and drop data from __sockpairR_, perhaps after my application calls _loop_misc_. This should also avoid wasting megabytes of socket buffers per MQTT connection.

**Comment by vadmium** [comment]
I bumped into Commit a6fc6c10194474965b104c249102b39b6d5b5645 (pointing to Issue #563), because it broke my workaround code. It looks like that change might fix the problems described here.

**Comment by MattBrittan** [comment]
I'm going to close this due to inactivity (and significant changes to the library since this was raised). If you are still experiencing the issue then please feel free to reopen. This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward).
