### ISSUE TITLE
MQTT Protocol

### ISSUE THREAD

**Issue by johansutanto** [eclipse/paho.mqtt.python#278]
Paho is using TCP protocol, and my broker is using MQTT protocol, is there any chance i can go with mqtt protocol? (mqtt://localhost:1883)

**Comment by johansutanto** [comment]
Thanks
Client(client_id="", clean_session=True, userdata=None, protocol=MQTTv311, transport="tcp")
So change the tcp into mqtt?

**Comment by Nzbuu** [comment]
As you have written it, you will get the MQTT protocol using a TCP socket.

**Comment by johansutanto** [comment]
Hmm, i dont think so,
Im using rabbitmq, which support mqtt in plugin, its bassically support, but it need mqtt://localhost:1883, ive been testing it.
Paho require tcp://localhost:1883, it works on mosquitto, but got error on rabbitmq, it say network error (5), ithing because tcp protocol is used by amqp in rabbitmq

**Comment by johansutanto** [comment]
Based on your comment, it cannot use mqtt://broker:1883 right?

**Comment by swails** [comment]
As @Nzbuu said, MQTT is a communication protocol -- it specifies how messages should be formatted in order to conform to the specification.  MQTT specifically is lightweight (unlike, say HTTP), so the amount of data that needs to be sent on connection is minuscule by comparison.

Since MQTT is a strictly a protocol, it is completely abstracted from the transport technology used (think TCP or UDP, for example).  I've only ever used MQTT over a TCP connection, and I strongly suspect that's what you need here.

The URLs you're posting here are generally of the format:

``<scheme>://<hostname>:<port>``

``<scheme>`` is there primarily to tell the client what to do.  Different clients may interpret ``<scheme>`` differently.  For instance, "https" in web browsers indicates that the web browser should utilize the http protocol secured via a TLS-encrypted TCP connection (notice that, like MQTT, HTTP is nothing more than a protocol for communication rather than a transport technology itself).

So when you see "mqtt://" in relation to RabbitMQ, that's telling you to use the MQTT protocol.  This is most likely because a RabbitMQ broker supports more than 1 different protocol.  However, the MQTT library here doesn't support multiple protocols.  It supports MQTT (over TCP and websockets).  So "mqtt://" isn't supported -- after all, it's not like the client library here knows how to handle another protocol (like http).  I've never used "tcp://" either.  I've only specified the hostname (or IP address) and the port number.  Something like this:

```python
client = Client()
client.connect('localhost', port=1883)
```

> Based on your comment, it cannot use mqtt://broker:1883 right?

Correct -- nowhere do you use `mqtt://broker:1883`.  You use `broker` for the server location (hostname or IP address) and 1883 for the port.  The `mqtt://` part is simply assumed because you're using an MQTT library.  The TCP part is specified as the transport layer in the `Client` constructor (the only other supported option is `websockets`, although the current client library will interpret anything that's not `websockets` as TCP).

**Comment by johansutanto** [comment]
Thanks for the detail
