### ISSUE TITLE
on_message load multiple time 

### ISSUE THREAD

**Issue by connect2robiul** [eclipse/paho.mqtt.python#287]
```
def on_message(client, userdata, message):
    with app.app_context():
        print(message.topic)

mqc = mqttc.Client()
mqc.on_connect = on_connect
mqc.on_message = on_message
mqc.on_publish = on_publish
mqc.connect('localhost',1883,60)
mqc.loop_start()
```

Publish code 

`mosquitto_pub -h localhost -t ccu -m "{'device':'CO74','message':'hello',}"`

for this single line of code, print comment execute multiple time which case error

**Comment by rbalik** [comment]
Have you tried a higher QOS level?

**Comment by connect2robiul** [comment]
no sure . can you please give me some example?

**Comment by rbalik** [comment]
Here's a good article on MQTT QOS levels: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels

For mosquitto_pub you can publish at QOS 2 by putting `-q 2` in the command.
In Paho when you subscribe to the topic, you'll want to subscribe at that QOS level too. The subscribe function takes a QOS level.

That being said, if you're at QOS 0 you probably shouldn't see repeat messages anyway so this might be unrelated.

**Comment by connect2robiul** [comment]
`message.qos ` value is zero here  see both code carefully 

```
def on_message(client, userdata, message):
    with app.app_context():
        print(message.topic)
        x = yaml.load(message.payload)
        admin_data = [x]
        socketio.emit('admin', admin_data)

mqc = mqttc.Client()
mqc.on_connect = on_connect
mqc.on_message = on_message
mqc.on_publish = on_publish
mqc.connect('localhost',1883,60)
mqc.loop_start()

& 

def on_message(client, userdata, message):
    with app.app_context():
        print(message.topic)
        x = yaml.load(message.payload)
        admin_data = [x]
        socketio.emit('admin', admin_data)

mqc = mqttc.Client()
mqc.on_connect = on_connect
mqc.on_message = on_message
mqc.on_publish = on_publish
mqc.connect('localhost',1883,60)
mqc.loop_forever()
```


1st one shows multiple messages and emit & server work properly 
2nd one shows the single message but emit & server is not working 

I need single message with proper emit & python server

**Comment by PierreF** [comment]
Did you have on_message called multiple for all messages or only sometime ? i.e. it is reproducible 100% of the time.
If yes, I need more information on how to reproduce this issue, as I don't get multiple on_message delivery. (in fact if the answer is not, more information are still welcome, since I never seen this behaviour).

Especially your code sample is never complete and don't include part like your subscription. Could you come with a minimal example which exhibit your issue ?

The subscription part is very interesting, because that may be your issue. If you are doing two subscription like "#" and "ccu", then the broker is allowed to send the message twice which means on_message() will be called twice, one for each message.

**Comment by connect2robiul** [comment]
I have multiple subscription. But broker is allow to sent only one subscription or topic at time.

**Comment by PierreF** [comment]
I'm not sure to understand last sentence. From what I've seen on the MQTT standard, if you have multiple subscription that overlap the broker may send "duplicated" message.
Could you print the mid of the message that you get twice ? If the mid is not the same, this is not a paho bug. Maybe a broker bug, but for me it's a misuse of MQTT.

**Comment by connect2robiul** [comment]
`mosquitto_pub -h localhost -t ccu -m "{'device':'CO74','message':'hello',}" -q 2`

I am trying with this code but the problem cannot be solved and QoS value is still 0

**Comment by connect2robiul** [comment]
I am not working with print section @PierreF . Give multiple messages on message section which is shown in the code

**Comment by MattBrittan** [comment]
I'm going to close this due to inactivity. If you are still experiencing the issue then please feel free to reopen (but please try to provide a minimal, reproducible, example). This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward). This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward).
