### ISSUE TITLE
Reconnect when host is changed

### ISSUE THREAD

**Issue by riccardoch** [eclipse/paho.mqtt.python#297]
In my application I have Master-Slave architecture, the slaves are connected to the master unit where _Mosquitto_ is running; if the Master is KO, a new Master is elected and the Slaves have to connect to the new broker. 

How can I create the new connection using the same client object? Paho doesn't offer a close method and `reinitialise()` allows only to reset the connection to the same Broker.

I tried to disconnect the client and to redefine the object, but often the socket to the old Broker is still opened.

**Comment by PierreF** [comment]
You should be able to re-call connect and provide another broker address. Please note that this will assume to be connected to the same/equivalent broker, so for example QoS 2 message waiting for pubcomp will resume as send pubrel, not send publish. If your two broker are not synchronized this will be an issue.

In this case, your last solution (disconnect and re-created a new Client() object) should work. Once disconnected your should not have a socket opened to old Broker. Your issue may be due to disconnect() being asynchronous. It queue the sending of disconnect message and actually close the socket once sent. Once the full disconnection is done, loop_forever() should return (or loop_stop() if you are using loop_start()/loop_stop()).

**Comment by MattBrittan** [comment]
I'm going to close this because it appears the question has been answered and it's been inactive for some time.
