### ISSUE TITLE
Publisher and subscriber loosing messages

### ISSUE THREAD

**Issue by shaloba** [eclipse/paho.mqtt.python#306]
System:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

Paho MQTT:

`paho-mqtt==1.3.1`

issue: 

- "client_sub.py" example as subscriber  and publisher (two different processes)
- VerneMQ as the MQTT broker

I have encountered with the following wired issues: 

1. process 1 publish 10,000 messages to the broker (on_publish callback didn't called 10,000 times) and the subscriber didn't got all the messages that sent to the broker
2. process 1 publish 10,000 with sleep 1 second between each publish (on_published called 10,000 times) but the subscriber pulled only 80-80% of the messages
3. publish 10,000 messages with another librery (NodeJS) and all the messages have been written and read by the pub/sub processes. 

* why I loosing the data with the paho-mqtt ? 
Do I need to configure the paho-mqtt in a different way from the example ? does it suppose to support batch of data transformation ? 
Thanks in advanced!

Shlomy.

**Comment by PierreF** [comment]
Hi,

I could think of max_queued_messages_set, but by default it's unlimited. Could you confirm you are not calling it with value smaller than 10000 ?
Which QoS level are you using ? (even it this should not matter normally. You just need to make sure you are connected before trying a QoS=0 message).
Have you tested sending with the NodeJS code and receiving using the Python code (and the other way) ? This may give clue if the issue is on the sender or receiver side.

If possible, could you share the code of your Python pub/sub  ?

**Comment by MattBrittan** [comment]
I'm going to close this due to inactivity (additional info requested but not provided). This is part of a general project to clean-up issues (which should make it simpler to identify priorities going forward).
