### ISSUE TITLE
Regarding max_inflight_messages_set

### ISSUE THREAD

**Issue by vrst37** [eclipse/paho.mqtt.python#337]
Hello,

Can I set the max_inflight_messages_set in runtime? Will it cause issues? 

Let's say I want to slow down the paho client (because my broker is having issues) then I can max_inflight_messages_set(1) and this will slow down the messages. Is this a good idea? Am I thinking correctly?

I read somewhere in documentation that max_inflight_messages_set should not be set after connect has been called however I do not see any reason why this is a problem.

**Comment by PierreF** [comment]
Is the answer in #338 the answer you need ?

Lowering the max_inflight message will slow down the message rate, but depending on your exact situation it may not be significant.
max_inflight mostly impact network with high latency, in low latency network it may have few to no impact at all.
Also, IIRC QoS = 0 are not counted at all in the max_inflght_message.

About changing max_inflght_message while connected, the issue it that it's not supported (mostly because not tested). It may work or may not work. The issue I could easily see is what happen when you have 10 messages inflight and reduce the the max_inflight to 5 ? Any part of code that assume current number of message inflight <= max_inflight will break.
