### ISSUE TITLE
Information about message_retry_set

### ISSUE THREAD

**Issue by vrst37** [eclipse/paho.mqtt.python#338]
Hello, 

Can I set the message_retry_set on runtime while the client is connected? Can I change this value without any negative consequences? I read on github documentation that this function should be set before connect. I do not understand why this is the case.

**Comment by PierreF** [comment]
Based on your other issue (#337  and #339) are you having trouble with message_retry that re-send message while your broker struggle processing the first one ?

As I said in #339, I think the message_retry is only used with historical TCP stack that were not reliable (TCP is supposed to never loose any byte. Either the connection is broken or nothing is lose). So for me this message_retry is not needed with a correct TCP stack.

Therefor if your issue is indeed re-send of message before broker handled them, you could disable message_retry... since the library does not allow to completely disable it, you may try setting it to arbitrary long value (e.g. 86400, you broker is probably able to process the message within 1 day :))

**Comment by vrst37** [comment]
Thanks man, makes sense :)
