### ISSUE TITLE
Hexadecimal  array send,    how  to  publish?

### ISSUE THREAD

**Issue by xcmg** [eclipse/paho.mqtt.python#351]
import paho.mqtt.publish as publish

intArr = [hex(11), hex(11), hex(12), hex(51), hex(21), hex(31), hex(31), hex(12)] #Hex send
publish.single("Data/F911",  intArr , hostname="host")

That 's  no response! 
How to do this？

**Comment by PierreF** [comment]
It's a bug that single hang like it does. The issue is that publish.single expect a single value (string, byte or bytearray) and not a list.
You will need to convert your intArr to a string (`''.join(intArr)`) before passing it to publish.single.

But I'm not sure that you really want to send that. Do you really want to use `hex()` ? If you want to send the binary string made of 8 bytes whose decimal value are 11, 11, 12, ...,  31, 12, then you should use
```
binary_value = bytearray([11, 11, 12, 51, 21, 31, 31, 12])
# OR
binary_value = b'\x0b\x0b\x0c3\x15\x1f\x1f\x0c'
publish.single("Data/F911", binary_value , hostname="host")
```

**Comment by ralight** [comment]
An exception is now raised if a list is passed, so I think this can be closed.
