### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by Leedayoung** [eclipse/paho.mqtt.python#358]
Is this client library thread-safe?
In my view, it is quite thread-safe by using threading.Lock() but I am not sure.

**Comment by swails** [comment]
Yes, it should be thread-safe.  If it's not, that's a bug.

That said, in multithreaded applications I've written utilizing this library, I usually instantiate a separate connection for each worker thread.

**Comment by t-xigit** [comment]
@swails  could you share some snippets regarding the workers?
Cheers

**Comment by AndrewCarterUK** [comment]
This library isn't thread safe at the moment (v1.5.0). We're getting deadlocks calling publish on a client from multiple threads.

**Comment by farzadpanahi** [comment]
What is the latest status on this issue for v1.6.1? Is the client library thread safe? Can I create one connection and use it in multiple threads to publish data or it should be one connection per thread?

**Comment by MattBrittan** [comment]
My answer is "we are aiming for a thread-safe library, and things improve with each release, but we probably have a way to go" (see PR's like #168). I realise that's not really a satisfactory answer but work is proceeding (and if you hit an issue, please do log an issue and provide as much information as you can!). 

On that basis I'm going to close this issue because I don't think it's particularly useful keeping it open (there are a few open issues covering specific thread safety issues).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
