### ISSUE TITLE
on_publish() called before publish() completes

### ISSUE THREAD

**Issue by mistotebe** [eclipse/paho.mqtt.python#361]
While trying to write an asyncio-friendly wrapper, I have this code:
```python
async def publish(self, *args, **kwargs):
    future = self.loop.create_future()
    result, mid = super().publish(*args, **kwargs)
    if result != mqtt.MQTT_ERR_SUCCESS:
        raise MQTTError(result)
    self.__in_flight[mid] = future
    return await future

def on_publish(self, client, userdata, mid):
    future = self.__in_flight.pop(mid)
    future.set_result(None)
```
The problem is that for `qos=0` messages, `on_publish` is being called somewhere from within `publish`, before it has returned the message id to us, so the above fails.

Is it possible to tell based on the `publish` result whether `publish` has completed all required actions succesfully (even when `qos>0`) or there is still work to be done and we have to wait for `on_publish`?

And how would one tell that a publish failed? - but feel free to redirect me to the protocol spec on this one if I'm missing something.

**Comment by jeeger** [comment]
I'm doing the exact same thing, and it is very annoying. `on_publish` is called directly, before the result is even returned. This makes sense from the standpoint of the library implementor, as `on_publish` on a QOS 0 publishing is not caused by an acknowledgement packet arriving, but by the package *leaving* the send queue (client.py:2112).

This also means that the documentation is partially incomplete – on QoS 0 messages, when `publish()` returns, the packet has indeed been sent, and thus, publishing has been successful, UNLESS the socket queue was full, in which case the `on_publish` callback would be called later by another thread. This makes it really hard to handle publishing messages with different QoS levels and correctly check for the sent state under an external event loop.

I see two possibilities here for us using an external event loop: Move the `on_publish` callback call into the `loop_misc` loop (but that loop is called only rarely), or somehow get the callback into the `loop_write` loop.

I don't have enough experience in the paho-mqtt codebase to decide on either solution, but I will have a look and post the solution here if I find one.

**Comment by mistotebe** [comment]
My main issue is that the message id has not been seen by us yet at the point of the callback (so we don't know how to mark it done), nor does the result of `publish()` indicate all work is complete and no further `on_publish()` callback is pending for it (so we don't need to wait for it either).

**Comment by mistotebe** [comment]
So happy if another result code was added that makes the distinction between "everything has been done" and "wait for on_publish with this `mid` if you want to know it's done" clearer. Or even returning `mid == None` in this case if that makes sense elsewhere?

**Comment by jeeger** [comment]
With the patch in the linked pull request, on_publish is called by another thread/event loop on all messages, also those with QoS 0.

On April 10, 2019 5:24:19 PM GMT+02:00, "Ondřej Kuzník" <notifications@github.com> wrote:
>My main issue is that the message id has not been seen by us yet at the
>point of the callback (so we don't know how to mark it done), nor does
>the result of `publish()` indicate all work is complete and no further
>`on_publish()` callback is pending for it (so we don't need to wait for
>it either).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/eclipse/paho.mqtt.python/issues/361#issuecomment-481737441

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by mistotebe** [comment]
The above wouldn't fix it for clients that don't use an event loop. The (not exactly documented?) way to deal with this is to use the `MQTTMessageInfo` that's returned directly rather than unpacking it.

If `msginfo.rc` is ok and `msginfo.is_published() == False`, we need to yield until `on_publish()` gets called, otherwise we're done already (and let `on_publish` ignore the fact that `mid` hasn't been registered yet).

**Comment by jeeger** [comment]
Hello!

Thanks for your feedback on this!

> The above wouldn't fix it for clients that don't use an event loop.

True.

> The (not exactly documented?) way to deal with this is to use the
> MQTTMessageInfo that's returned directly rather than unpacking it.
> If msginfo.rc is ok and msginfo.is_published() == False, we need to
> yield until on_publish() gets called, otherwise we're done already
> (and let on_publish ignore the fact that mid hasn't been registered
> yet).

I'll try it out. It will be nice not having to rely on my own branch of 
mqtt-python.

Best regards,
Jan
