### ISSUE TITLE
asyncio loop_forever

### ISSUE THREAD

**Issue by au190** [eclipse/paho.mqtt.python#364]
Hi All

Iam using asyncio of this lib, as in the exemple
But when the server stops and start the client is not conecting back.
The loop_forever is blocking, not good for me.

Can you advice help ?

**Comment by swails** [comment]
`loop_forever` is blocking.  It's designed for single-thread execution, mainly.

If you want a multithreaded client, look at `loop_start()` and `loop_stop()` -- those are non-blocking.

**Comment by swails** [comment]
Oh, I misunderstood your question.

There are a couple approaches you can take.  One thing you can do (which I've done), is add a reconnection attempt to the `on_disconnect()` callback.  I'm not particularly fond of that approach, but it was fast and I wasn't trying to do anything complex enough with my client that I would wind up paying for it later.

**Comment by drmikecrowe** [comment]
@swails Did you find your `on_disconnect` logic worked better than the `loop_forever` reconnect?  I'm getting generic errors (`rc==1`) disconnects and debating if my backoff/reconnect logic should be dumped and replaced with the `loop_forever` running in a separate thread

**Comment by saimigo** [comment]
I have same question，is there some solutions？ please.

**Comment by MattBrittan** [comment]
I'm going to close this due to it's age and lack of detail (it appears some comments may have been removed). The `loop_asyncio.py` demo does not implement any reconnection logic currently (but it's fairly specialised so I'd suggest using `loop_start()` unless you need the async functionality). 

If this is still an issue (and for @saimigo) then please re-open, but include full details of your requirements, logs, sample code etc (as you will note by the lack of response to this ticket, this project has limited resources, meaning we may have to close issues that don't provide sufficient details).
