### ISSUE TITLE
 paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error when connecting to AWS IoT over websocket

### ISSUE THREAD

**Issue by smoothwood** [eclipse/paho.mqtt.python#381]
Hi All,

I appended below two lines to aws_iot.py and replace the host, access key and secret key with mine. When I call example_use() function, I always get this error: paho.mqtt.client.WebsocketConnectionError: WebSocket handshake 

    client.connect("a3f3ep261pa8dz-ats.iot.ap-northeast-1.amazonaws.com",443)

    client.loop_start()

**Comment by lwh31415** [comment]
https://github.com/eclipse/paho.mqtt.python/issues/277

1. the only header you need to set is Host
2.before connect, you need client.tls_set()

**Comment by SeleniumUser** [comment]
i am also getting same error

**Comment by petergerten** [comment]
same issue here

**Comment by MattBrittan** [comment]
I'm going to close this due to its age and the minimal information provided. Please feel free to reopen but please provide a minimal, reproducible example (we cannot help unless we can see how you have configured `client`).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
