### ISSUE TITLE
subscribe simple freeze when auth is wrong

### ISSUE THREAD

**Issue by Mendes11** [eclipse/paho.mqtt.python#404]
When I try to subscribe to a specific topic using single, if my auth configuration is wrong the code freezes and never return or throw any error. I think it just keeps trying.

Is there any way to configure a timeout? I went to single and connect methods docs and saw that there isn't an option for timeout.

I detected this problem by configuring mosquitto with allow_anonymous = false and then tried to connect using auth = None.

**Comment by MattBrittan** [comment]
I believe that #470 was a duplicate of this issue and, in that issue, @sparky8512 reported:

>I tracked it down to an exception being swallowed from the on_connect handler publish.multiple (and therefor publish.single) uses. I believe it got fixed by https://github.com/eclipse/paho.mqtt.python/commit/88688d85d3d6307a3da11c97d77dc1e29b52453a. After updating to paho-mqtt-1.5.1, I no longer get the blocking forever behavior.

Hopefully that resolves the main focus of this issue; the other portion is the need for a timeout and I'll make issue #655 the primary issue for that.

As a result I'm going to close this issue (given the number of years passed!); if you retest and the issue still exists then please do reopen this (and apologies for the lack of response to this issue!).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
