### ISSUE TITLE
Bad network cause too many time_wait connections

### ISSUE THREAD

**Issue by zjalen** [eclipse/paho.mqtt.python#430]
I have a client program running on **raspiberry**.Sometimes the network environment is bad.My MQTT broker server show thousands of **time_wait** connections from the same client.Even the server will be out of response.
```shell
$ netstat -an |grep ":9898"
tcp        0      0 127.0.0.1:9898              125.90.0.11:41378             TIME_WAIT
tcp        0      0 127.0.0.1:9898              125.90.0.11:41379             TIME_WAIT
tcp        0      0 127.0.0.1:9898              125.90.0.11:39352             TIME_WAIT
tcp        0      0 127.0.0.1:9898              125.90.0.11:39350             TIME_WAIT
tcp        0      0 127.0.0.1:9898              125.90.0.11:35763             TIME_WAIT
tcp        0      0 127.0.0.1:9898              125.90.0.11:39372             TIME_WAIT
tcp        0      0 127.0.0.1:9898              125.90.0.11:39373             TIME_WAIT
tcp        0      0 127.0.0.1:9898              125.90.0.11:41176             TIME_WAIT
...
```
I don't know how to resolve this.

**Comment by MattBrittan** [comment]
I'm going to close this due to the elapsed time (sorry there was no response earlier). If you are still having issues them please feel free to reopen this but we will need to be able to duplicate the issue so if you could share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that would be really helpful.
