### ISSUE TITLE
Publish message to a specific client ID

### ISSUE THREAD

**Issue by bcashier** [eclipse/paho.mqtt.python#433]
Hi,

Is it possible to publish message to a specific client id ?

I want to publish two things using mqtt:
1- General informations like users scores, stats etc ... and can be viewable by everyone.
2- Sensitive informations reserved for private user like own score, name etc ...

Is there any clean way to do it using Paho MQTT ?

Thank you

**Comment by mbenabda** [comment]
MQTT is pub/sub. point to point messaging can be achieved but is not what the protocol was designed for.
You could publish an encrypted payload to a topic that is specific to your recipient (ex: point-to-point/${recipient id}), and setup your broker's access control so that only that recipient is allowed to subscribie to that topic

**Comment by ralight** [comment]
I'm closing this issue because you've received a relevant answer above, and it's not related to the Python client particularly. If you disagree, please reopen and provide more details.
