### ISSUE TITLE
def on_connect(client, userdata, rc) give no error using python3

### ISSUE THREAD

**Issue by cymplecy** [eclipse/paho.mqtt.python#434]
I've used

```
def def on_connect(client, userdata, rc):
    print("Connected with result code " + str(rc))
```
in python2 for many years

Switched to using python3 and the print is never seen when connecting

Googling found I should use
```
def def on_connect(client, userdata, flags, rc):
```
Issue is - should I not receive error message if function definition is wrong?

**Comment by josiahwitheford** [comment]
You have written `def def` here instead of just `def`. Is that the same as in your code or just a typo here?

**Comment by cymplecy** [comment]
Checking my orig Python 2 code I did use
![image](https://user-images.githubusercontent.com/2357428/70397398-c6c44200-1a09-11ea-9946-b77311b73603.png)

I don't know how I managed to mangle my original post!

Thanks for pointing it out :)

**Comment by ralight** [comment]
The on_connect docs say:
```
        Expected signature for MQTT v3.1 and v3.1.1 is:
            connect_callback(client, userdata, flags, rc, properties=None)

        and for MQTT v5.0:
            connect_callback(client, userdata, flags, reasonCode, properties)
```

You wouldn't have seen an error because of #365, which now has an open PR. I think in essence that means this is a duplicate: even though it's not exactly the same issue you would have found the problem if that had been fixed. You have the answer to your specific problem above, and the more general problem of errors is addressed in #365.

**Comment by ralight** [comment]
I'm closing this because I believe it has been addressed.

**Comment by wagnerengenhoca** [comment]
Como recebo minha mensagem como string em vez de bytes?
