### ISSUE TITLE
No error when publish message fails with QoS 1 or 2

### ISSUE THREAD

**Issue by aymeric-soubrouillard** [eclipse/paho.mqtt.python#440]
# Context
If a deconnection occurred between connection & publishing a message the client return 0 which is the MQTT_ERR_SUCCESS while it has not been delivered.

# How to reproduce
```
client = mqtt.Client()
client.connect("localhost", 1883)
time.sleep(15)
# Shutdown the server
publish_result = client.publish(topic="test", payload="Testing publish", qos=1, retain=False)
print(publish_result.rc)
> 0
# Should be an MQTT_ERR_* int
```

# Additional note
Why call a success code MQTT_ERR_SUCCESS. Is it an error or a success?! very confusing.

**Comment by pshem** [comment]
Same problem. I can get `client.is_connected() == False && publish_result.is_published() == true`, which just feels wrong. The only way to check I've come up with is timing out `publish_result.wait_for_publish()` - if it doesn't return in 5s, it failed. However, this doesn't feel like a proper solution.

 `paho.mqtt.publish.single()` also gives no indication to whether the message was accepted(for example due to an authentication failure), regardless of QoS.

**Comment by smilife-chocolat** [comment]
Have you check this know limitations on doc : https://github.com/eclipse/paho.mqtt.python#known-limitations ?

**Comment by MattBrittan** [comment]
Unfortunately handling errors publishing QOS1/2 messages will always be a bit confusing. This is because these messages are queued and may be sent when/if the connection comes back up (and the acknowledgment process, especially with QOS2, may take a while to complete). If you wish to confirm delivery then register an `on_publish` callback (which will be notified when a PUBACK is received from the broker).

Given this issues age I'm going to close it. I did attempt to duplicate the issue with the latest release (code/results below) but it worked as expected. If this remains an issue please reopen the issue but supply [logs](https://github.com/eclipse/paho.mqtt.python#enable_logger) to enable us to see what is happening.

```
import paho.mqtt.client as mqtt
import time


def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))


client = mqtt.Client()
client.on_connect = on_connect
client.loop_start()
client.connect("host.docker.internal", 1883)
time.sleep(15)
# Shutdown the server
publish_result = client.publish(topic="test", payload="Testing publish", qos=1, retain=False)
print(publish_result.rc)
```

Output:

```
Attaching to pythondocker-1
pythondocker-1  | Connected with result code 0
pythondocker-1  | 4
pythondocker-1 exited with code 0
```
