### ISSUE TITLE
Failed to receive on socket: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by marcomiglionico94** [eclipse/paho.mqtt.python#459]
I am using paho.mqtt on a Jetson Nano and I am running the following example code from https://www.cloudmqtt.com/docs/python.html using my connection credentials.

The problem is that I am getting the following error:
"failed to receive on socket: [Errno 104] Connection reset by peer".

If I run the same code on my Mac instead of the Jetson Nano it is working

**Comment by vnrgoli** [comment]
Did you fix this? I am getting same error on Raspi.

**Comment by MattBrittan** [comment]
The error is to be expected if the connection drops (which can happen). More information (e.g. your code, details of what happens - does this cause the loop to stop etc) would be needed to assist.

However as this issue is quite old I'm going to close it; if you are still having the issue (with the latest release) then please feel free to reopen (ideally with more info).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
