### ISSUE TITLE
publish.single blocks forever when authentication fails

### ISSUE THREAD

**Issue by stereobutter** [eclipse/paho.mqtt.python#470]
When using `publish.single` to publish a message to a broker and one used an invalid `username` and/or `password` the call blocks forever. I would have expected this to raise an exception; is this the intended behavior? 

**Disclaimer**: This might be the same issue as https://github.com/eclipse/paho.mqtt.python/issues/355, I don't know, since the issue description there is rather long winded and unclear.

**Comment by sparky8512** [comment]
FYI: Saw this issue while looking into same symptom, using paho-mqtt-1.5.0.

I tracked it down to an exception being swallowed from the on_connect handler publish.multiple (and therefor publish.single) uses. I believe it got fixed by 88688d85d3d6307a3da11c97d77dc1e29b52453a. After updating to paho-mqtt-1.5.1, I no longer get the blocking forever behavior.

**Comment by MattBrittan** [comment]
Closing this based on the comment above and lack of further activity.
