### ISSUE TITLE
delayed messages and infinite buffer

### ISSUE THREAD

**Issue by mhechthz** [eclipse/paho.mqtt.python#483]
Hi,

I'm not sure wether this is the right place to post but my problem is in combination with mosquitto as well as activeMQ.

I use mosquitto with paho-mqtt to send jpegs (ca. 50 kB) from camera to a light weight video server that stores the images in a database. Both sides work with paho-mqtt. What I see now is that the camera advances the stored images, i.e. after a few minutes there is a time gap of at least a minute. Obviously the publisher publishes faster than the broker can transmit or the subscriber can read. After 4 hours there is a gap of about 2 hours. **No frame is dropped**, so the mqtt-broker(s) seem to buffer the images. I don't want this behaviour, but want that only one image is buffered.

I do the following:
```
  client = mqtt.Client('myCameraClient', clean_session=True)
  client.max_queued_messages_set(1)
  client.max_inflight_messages_set(1)
  client.connect('brokeraddress', 1883, 60)
```
What is wrong here? Is it paho-mqtt, is it my code or is it the configuration of broker?

**EDIT:**
What I see is, that the publisher consumes an increasing amount of memory, so the publisher is buffering the messages!

**EDIT 2:**
Meanwhile I changed the code getting it working:
```
      msgInfo = client.publish("stream/camera", encFrame,  qos=0, retain=False)  
      while msgInfo[1] - publishedMID>=2:
        print("DELAY:",msgInfo[1],publishedMID,"... sleep 0.05s ...")
        time.sleep(0.05)
```
`publishedMID` I get from `on_publish`, i.e. I wait until the buffer is less than 2 messages. This means that I drop the messages myself manually, but expected that the mqtt "system" is doing this for me.

**Comment by MattBrittan** [comment]
This is the expected behaviour; if you call `publish` the library will make an attempt to publish it (the exact behaviour depends upon the QOS level used).  `publish` adds the message to an internal queue (`_out_packet`) and there is currently no mechanism to limit this queue.

`max_queued_messages_set` and `max_inflight_messages_set` have no impact at QOS0 (a message is "inflight" if we are waiting for a response from the server, QOS1 is fire and forget so there is no response).

Note that your solution will break down when the MID reaches 65535 and resets to 1 (keeping a count of messages you have published but not received the callback for might be a better option).

Due to the age of this issue I'm going to close it (sorry no one responded earlier); if you are still having issues then please feel free to reopen it.
