### ISSUE TITLE
wss:// url string cannot be used

### ISSUE THREAD

**Issue by jax79sg** [eclipse/paho.mqtt.python#489]
Hi, i am trying to use Paho Client to connect to a mqtt via the following URL ( `wss://usr:pw@host:port/mqtt` ) without success. The url is a https gateway that authenticates with `usr` and `pw` before forwarding to the MQTT server. How should i get this to work? The code below couldn't work.

```
self.client = mqtt.Client(client_id="mqClientName", transport="websockets" 
self.client.username_pw_set(username=usr, password=pw)
self.client.tls_set(cert_reqs=ssl.CERT_NONE)
self.client.tls_insecure_set(True)
self.client.on_connect=self.__on_connect__
self.client.on_message=self.__on_message__
self.client.connect(host, port)
```
I get the following error.

```
/venv/lib/python3.6/site-packages/paho/mqtt/client.py", line 3643, in _do_handshake
    raise WebsocketConnectionError("WebSocket handshake error")
paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error
```

The URL string works fine for the Android Java Paho Client though.

Any advice here?
Thank you.

**Comment by imperialguy** [comment]
Are there any plans to add this feature soon? It will be very useful for users who don't want to connect using a port, instead we just want to use a wss://url.

**Comment by MattBrittan** [comment]
I'm going to close this issue due to it's age and a need for more information. The library does support web-socket connections but it's difficult for us to diagnose issues that we cannot duplicate; if you are still having issues please reopen this issue but, ideally, provide an example trying to connect to a public broker (e.g. `mqtt.eclipseprojects.io` or `test.mosquitto.org`). Alternatively (but not as good) use a test page to connect (e.g. [hive client](https://www.hivemq.com/demos/websocket-client/)) and include a screenshot so we can see what options were selected.

@imperialguy This library accepts a host & port (passed to `connect`) and a `path` (defaults to `/mqtt` but can be set with `ws_set_options`). The library does not currently use URL's and there are no current plans to add this (if you are keen to add this then please raise an issue with a proposal).
