### ISSUE TITLE
on_disconnect not working as expected 

### ISSUE THREAD

**Issue by mpena2099** [eclipse/paho.mqtt.python#552]
Hello. 

The "on_disconnect" callback is not triggered when the internet connection is interrupted, but only when the program is killed.

I needed to execute a command every time the connection to the broker is lost ...

**Comment by jpodpro** [comment]
i'm finding that we ocasionally get disconnected from the broker and the callback is not fired nor is a reconnect attempted. we simply notice that it has stopped functioning and have to restart the server.

**Comment by kinslayer1982** [comment]
I can confirm this behaviour for 1.5.1
In 1.5.0 reconnect is working.

**Comment by stsdc** [comment]
Can confirm this issue. You may try just add a rule to Your router to block certain URL to reproduce this issue.

**Comment by MattBrittan** [comment]
Unfortunately without [logs](https://github.com/eclipse/paho.mqtt.python#enable_logger) it's difficult to respond to issues like this  (there are many potential causes; some OS dependent). Given this issues age (there have been a few releases since) I'm going to close it. If anyone is able to replicate the issue then please reopen it and supply logs to enable us to diagnose further (include details of the library version in use, OS, network setup etc).
