### ISSUE TITLE
Keepalive ping requests with a subscribe only client are sent unnecessarily.

### ISSUE THREAD

**Issue by CmpCtrl** [eclipse/paho.mqtt.python#607]
In the `_check_keepalive` function, a ping request will be sent if either the time since last msg in OR last msg out is over the keep alive limit. In my application where I am only subscribed to a topic and never publish, it continuously sends ping requests at the keepalive time. I would prefer the logic below use an AND in place of the OR so that a received message will also reset the keepalive time. 

https://github.com/eclipse/paho.mqtt.python/blob/71e29222421b83774af8c241898d4f1f15f58b8d/src/paho/mqtt/client.py#L2405-L2415

The server I am working with seems to only need a ping to keep the connection alive if the time since last message in AND last message out are over the timeout. Is it common for other servers to require a ping if either are over the timeout?

**Comment by ralight** [comment]
@CmpCtrl From what I can see, everything is working exactly as I'd expect. I've tried a test connecting to mosquitto and subscribing only to `$SYS/broker/uptime`, which is updated every ten seconds. The client has a keepalive of 60 seconds, and I see it sending a PINGREQ every 60 seconds. This is what the MQTT spec requires. If you're seeing disconnects within the keepalive interval, then either the server is doing something odd (perhaps disconnecting clients at exactly the keepalive instead of keepalive*1.5) or there is a separate network problem like you suggest.
