### ISSUE TITLE
async message_callback_add

### ISSUE THREAD

**Issue by panla** [eclipse/paho.mqtt.python#630]
```python
client.message_callback_add(topic, callback)

async callback(client, userdata, msg):
    await ...
    pass

```

```text
how can i use an async func to message_callback_add
```

**Comment by MattBrittan** [comment]
I'm going to close this due to it's age and the low level of detail provided. Please feel free to reopen but please describe your requirement in more detail (alternatively, you are likely to get an answer more quickly at stackoverflow but would definitly need more detail there).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
