### ISSUE TITLE
Validator Function

### ISSUE THREAD

**Issue by sfphh4** [eclipse/paho.mqtt.python#644]
I am looking for a validator function for topic. I have a bunch of strings and I need to check if the strings are a valid mqtt topic or not.

What is the best way to achieve this?

I do not want to use regex to do this, and am hoping to use some function in the library already implemented to achieve this.

**Comment by MattBrittan** [comment]
The [v3 spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718039) sets the following requirements for the topic name:

>The Topic Name MUST be present as the first field in the PUBLISH Packet Variable header. It MUST be a UTF-8 encoded string [MQTT-3.3.2-1] as defined in section 1.5.3.   
>The Topic Name in the PUBLISH Packet MUST NOT contain wildcard characters [MQTT-3.3.2-2].   
>The Topic Name in a PUBLISH Packet sent by a Server to a subscribing Client MUST match the Subscription’s Topic Filter according to the matching process defined in Section 4.7  [MQTT-3.3.2-3]. However, since the Server is permitted to override the Topic Name, it might not be the same as the Topic Name in the original PUBLISH Packet.

So anything that meets the above is potentially a valid topic. I somehow think you have something else in mind when you say "valid mqtt topic" but without extra detail this is not possible to answer further.

Due to the age of the issue (sorry it took so long to reply!) I'm going to close it for now (hopefully the above is of some use).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
