### ISSUE TITLE
Can subscribe.simple accept a list of topics and return a list of values?

### ISSUE THREAD

**Issue by optio50** [eclipse/paho.mqtt.python#645]
Can "subscribe.simple" accept a list and return a list?

I am not able to have a list returned when a list is subscribed to

topic = ["$SYS/broker/connection/raspberrypi.test-mosquitto-org/state", "$SYS/broker/connection/raspberrypi.br-home"]  
print(topic)  
msg = subscribe.simple(topic, msg_count=2, hostname="test.mosquitto.org")  
print(msg.payload)

**Comment by MattBrittan** [comment]
`subscribe.simple` can accept a list of topics (and will subscribe to all topics). It returns a list of messages; for example:

```
import paho.mqtt.subscribe as subscribe

topics = ["$SYS/broker/clients/maximum", "$SYS/broker/messages/received"]

m = subscribe.simple(topics, hostname="mosquitto", retained=False, msg_count=2)
for a in m:
    print(a.topic)
    print(a.payload)
```

Output:

```
pythondocker-1  | $SYS/broker/clients/maximum
pythondocker-1  | b'1'
pythondocker-1  | $SYS/broker/messages/received
pythondocker-1  | b'6'
```

I'm not sure if that really answers your question (but it shows what `simple` does`).

Given the age of the issue and the fact that the above probably answers the questions I'm going to close this. Please do reopen if you have further questions (but please provide more detail and show what you have tried).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
