### ISSUE TITLE
thread problem

### ISSUE THREAD

**Issue by wttt-py** [eclipse/paho.mqtt.python#647]
When I use multiple threads, such as connecting 5,000 terminals to send data, it is normal for me to send data once every 10 seconds, and the thread will freeze after a while, as long as the message rate is fast, the thread will freeze directly. live. How to solve this problem, thanks

**Comment by sfphh4** [comment]
so you have 5000 instances of mqtt client? And all of them are running their own managed thread?

**Comment by MattBrittan** [comment]
I'm going to close this due to inactivity (a question was asked and not answered). Solving this kind of issue is likely to be tricky and we would need a lot more info (your code, logs etc). There are a few situations (covered in other issues) where the process may freeze; hopefully many of these are dealt with in the next release (but I'd guess we have not found them all and will need users help to find them).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
